# Generated by Django 2.2.4 on 2019-08-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team or Department', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task Name', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, default=0, null=True)),
                ('duration_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('due_date', models.DateTimeField()),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Owner')),
                ('stakeholders', models.ManyToManyField(blank=True, to='tasks.Stakeholder')),
            ],
            options={
                'ordering': ['due_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task Name', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, default=0, null=True)),
                ('duration_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('due_date', models.DateTimeField()),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Owner')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'ordering': ['due_date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Person'),
        ),
    ]
