# Generated by Django 2.2.4 on 2019-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='worktime',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=300),
        ),
    ]
